version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src 
    ports:
      - "8080:8080"  
    environment:
      DATABASE_URL: postgres://user:example@db:5434/ezymatrics 
    depends_on:
      - db

  db:
    image: postgres:13 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ezymatrics 
    ports:
      - '5434:5432'

volumes:
  postgres_data:
